version: '3'
services:
    location:
        image: microcoffeeoncloud-location:1.0.0-SNAPSHOT
        ports:
            - "8081:8081"
            - "8444:8444"
        links:
            - mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=devdocker
            - SPRING_CLOUD_CONFIG_URI=https://192.168.99.100:8454
        domainname: microcoffee.study
    mongodb:
        image: microcoffeeoncloud-database:1.0.0-SNAPSHOT
        command: mongod --sslMode preferSSL --sslPEMKeyFile /microcoffee.study-key.pem --bind_ip_all
        ports:
            - "27017:27017"
            - "28017:28017"
        volumes:
            - mongodbdata:/data/db
volumes:
    mongodbdata:
        external: true
