version: '3'
services:
    creditrating:
        image: microcoffeeoncloud-creditrating:1.0.0-SNAPSHOT
        ports:
            - "8083:8083"
            - "8446:8446"
        environment:
            - SPRING_PROFILES_ACTIVE=devdocker
            - SPRING_CLOUD_CONFIG_URI=http://192.168.99.100:8091
