version: '3'
services:
    discovery:
        image: microcoffeeoncloud-discovery:1.0.0-SNAPSHOT
        ports:
            - "8092:8092"
            - "8455:8455"
        environment:
            - SPRING_PROFILES_ACTIVE=devdocker
            - SPRING_CLOUD_CONFIG_URI=https://192.168.99.100:8454
        domainname: microcoffee.study
            